env: 
    git_token: "ENCRYPTED[!a17a942695eb3d62f4a8395586cfe3f69bf9259ee9c4dbe94eed3cda627ed1703b68f74a638304bcdc6fb701283530ce!]"

task:
  name: "Bobo-Bot"
  timeout_in: 240m  
  container:
      image: marvelmathesh/docker:rom
      cpu: 8
      memory: 32G

  Get-Requirements_script:
      - apt update && apt upgrade && echo "yes"
      - sudo -E apt-get -qq update
      - sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev rsync flex bison ccache openjdk-8-jdk expect neofetch tmux tmate aria2
      - curl -sL https://git.io/file-transfer | sh

  Clone-Tool-and-Setup:
      - git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git -b master ErfanGSIs
      - sudo chmod -R 0777 ErfanGSIs
      - sudo bash ErfanGSIs/setup.sh

  Get-Configs_script:
      - java -jar Bobo.jar
      - rm -rf configs/configs.prop && rm -rf configs/sf-creds.prop
      - cd configs
      - git clone https://Subhendu-droid:${git_token}@github.com/Subhendu-droid/cosmic-env PR
      - cp PR/configs.prop configs
      - cp PR/sf-creds.prop configs

  Run-Bot_script:
      - sudo chmod -R 0777 *
      - sudo java -jar Bobo.jar
